version: "3.0"

services:

    db_mongodb:
        image: mongo
        container_name: ${CONTAINER_NAME_MONGODB}
        restart: unless-stopped
        environment:
            - PUID=1000
            - PGID=1000
        ports:
            - ${PORT_MONGODB}:27017
        volumes:
            - ${VOLUME_LOCATION_MONGODB}:/data/db

    db_mysql:
        image: mysql
        container_name: ${CONTAINER_NAME_MYSQL}
        restart: unless-stopped
        tty: true
        ports:
            - "${DATABASE_PORT_MYSQL}:3306"
        volumes:
            - ${VOLUME_LOCATION_MYSQL}:/var/lib/mysql
        environment:
            MYSQL_ALLOW_EMPTY_PASSWORD: 'true'
            MYSQL_DATABASE: ${DATABASE_NAME_MYSQL}
            MYSQL_ROOT_PASSWORD: ${DATABASE_PASS_MYSQL}

    db_postgres:
        image: postgres:16.0-alpine
        container_name: ${CONTAINER_NAME_POSTGRES}
        environment:
            POSTGRES_DB: ${DATABASE_NAME_POSTGRES}
            POSTGRES_USER: ${DATABASE_USER_POSTGRES}
            POSTGRES_PASSWORD: ${DATABASE_PASS_POSTGRES}
        volumes:
            - ${VOLUME_LOCATION_POSTGRES}:/var/lib/postgresql/data
        ports:
            - "${DATABASE_PORT_POSTGRES}:5432"

    db_sql-server:
        image: mcr.microsoft.com/mssql/server:2017-latest-ubuntu
        container_name: ${CONTAINER_NAME_SQLSERVER}
        environment:
            ACCEPT_EULA: "Y"
            SA_PASSWORD: ${DATABASE_PASS_SQLSERVER}
            MSSQL_PID: ${DATABASE_PID_SQLSERVER}
        ports:
            - "${DATABASE_PORT_SQLSERVER}:1433"
        volumes:
            - ${VOLUME_LOCATION_SQLSERVER}:/var/opt/mssql/data

    pg_admin_container:
        image: dpage/pgadmin4:latest
        container_name: ${CONTAINER_NAME_PGADMIN}
        ports:
            - "${PORT_PGADMIN}:80"
        volumes:
            - ${VOLUME_LOCATION_PGADMIN}:/var/lib/pgadmin
        environment:
            PGADMIN_DEFAULT_EMAIL: ${DEFAULT_EMAIL_PGADMIN}
            PGADMIN_DEFAULT_PASSWORD: ${DEFAULT_PASS_PGADMIN}
