version: "3.0"

services:
  postgres:
      image: postgres:14-alpine
      container_name: ${CONTAINER_NAME}
      environment:
        POSTGRES_DB: ${DATABASE_NAME}
        POSTGRES_USER: ${DATABASE_USER}      
        POSTGRES_PASSWORD: ${DATABASE_PASS}
      volumes:
        - ./pgdata:/var/lib/postgresql/data
      ports:
        - "${DATABASE_PORT}:5432"
      