version: "3.0"
services:
  db_mongodb:
    image : mongo
    container_name: mongodb_container
    restart: unless-stopped
    environment:
     - PUID=1000
     - PGID=1000
    ports:
     - 27017:27017
    volumes:
     - ./mongodb:/data/db
    