version: "3.0"
services:
  db_postgres:
    image: postgres
    container_name: postgres_container
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASS}
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - "${DATABASE_PORT}:5432"
